# Generated by Django 4.2.13 on 2026-05-08 08:39

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', '社区管理员'), ('elder', '老年用户')], default='elder', max_length=10, verbose_name='角色')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='手机号')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('area', models.CharField(blank=True, max_length=100, null=True, verbose_name='居住片区')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像')),
                ('family_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='家属手机号')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户列表',
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='活动名称')),
                ('activity_type', models.CharField(choices=[('sports', '文体运动'), ('health', '健康讲座'), ('culture', '文化娱乐'), ('social', '社交联谊'), ('learning', '学习教育'), ('other', '其他')], default='other', max_length=20, verbose_name='活动类型')),
                ('description', models.TextField(blank=True, verbose_name='活动介绍')),
                ('location', models.CharField(max_length=200, verbose_name='活动地点')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('register_deadline', models.DateTimeField(verbose_name='报名截止时间')),
                ('max_participants', models.IntegerField(default=50, verbose_name='最大参与人数')),
                ('current_participants', models.IntegerField(default=0, verbose_name='当前报名人数')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='活动海报')),
                ('status', models.CharField(choices=[('draft', '待发布'), ('open', '报名中'), ('ongoing', '进行中'), ('finished', '已结束'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('target_group', models.CharField(blank=True, max_length=200, verbose_name='面向人群')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_activities', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动列表',
                'db_table': 'activity',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('ann_type', models.CharField(choices=[('notice', '通知公告'), ('activity', '活动提醒'), ('system', '系统消息')], default='notice', max_length=20, verbose_name='类型')),
                ('is_top', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('publish_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
                ('target_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='elderly_system.activity', verbose_name='关联活动')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告列表',
                'db_table': 'announcement',
                'ordering': ['-is_top', '-publish_time'],
            },
        ),
        migrations.CreateModel(
            name='ActivityStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_registered', models.IntegerField(default=0, verbose_name='总报名人数')),
                ('total_signed_in', models.IntegerField(default=0, verbose_name='总签到人数')),
                ('sign_in_rate', models.FloatField(default=0.0, verbose_name='签到率')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='统计更新时间')),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='elderly_system.activity', verbose_name='活动')),
            ],
            options={
                'verbose_name': '活动统计',
                'verbose_name_plural': '活动统计列表',
                'db_table': 'activity_stats',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', '已报名'), ('signed_in', '已签到'), ('cancelled', '已取消')], default='registered', max_length=20, verbose_name='状态')),
                ('register_time', models.DateTimeField(auto_now_add=True, verbose_name='报名时间')),
                ('sign_in_time', models.DateTimeField(blank=True, null=True, verbose_name='签到时间')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/', verbose_name='签到二维码')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='elderly_system.activity', verbose_name='活动')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '报名记录',
                'verbose_name_plural': '报名记录列表',
                'db_table': 'registration',
                'ordering': ['-register_time'],
                'unique_together': {('user', 'activity')},
            },
        ),
    ]
