# Generated by Django 4.2.13 on 2026-05-08 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elderly_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='新闻标题')),
                ('content', models.TextField(verbose_name='新闻内容')),
                ('category', models.CharField(choices=[('policy', '政策资讯'), ('health', '健康养生'), ('activity', '活动动态'), ('notice', '社区通知'), ('other', '其他')], default='other', max_length=20, verbose_name='新闻分类')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='news_covers/', verbose_name='封面图片')),
                ('is_top', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('views', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('publish_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_list', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '新闻资讯',
                'verbose_name_plural': '新闻资讯列表',
                'db_table': 'news',
                'ordering': ['-is_top', '-publish_time'],
            },
        ),
    ]
