# Generated by Django 4.2.13 on 2026-05-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elderly_system', '0002_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='announcement_covers/', verbose_name='封面图片'),
        ),
        migrations.AddField(
            model_name='news',
            name='source',
            field=models.CharField(blank=True, default='社区发布', max_length=100, verbose_name='来源'),
        ),
    ]
